### ISSUE TITLE
压测了一下

### ISSUE THREAD

**Issue by XiaoMiku01** [FishZe/go-bili-chat#20]
![image](https://user-images.githubusercontent.com/54094119/224107426-6d62ba17-879f-4e36-9974-cc53ab3c4da0.png)
腾讯云 linux 4C8G 
连了B站在线的所有房间(大概),3w+
CPU占用在 30%-60% 压力不是很多
内存占了 7G+,然后就oom被系统kill了

**Comment by FishZe** [comment]
好的，感谢🙏
为什么我上次压测的数据那么奇怪..我有空再重测一下
用的是dev分支的最新版本吗？

**Comment by XiaoMiku01** [comment]
是的

**Comment by XiaoMiku01** [comment]
在windows下1.2个房间大概占用内存 3G，但是连接效率远不如linux

**Comment by FishZe** [comment]
我刚刚测试了5000个直播间.
上海腾讯云4C8G10M, cpu 6%, 内存510M
开3w个房间内存占7G+是否有点太夸张了, 还是说大量连接时会占用更多的内存?
