### ISSUE TITLE
UID为0会有问题

### ISSUE THREAD

**Issue by niaiai** [FishZe/go-bili-chat#33]
https://github.com/FishZe/go-bili-chat/blob/f7140706268735b05bfac0e28c02fae13fbd5c90/client/client.go#L87C40-L87C40

WsAuthBody中的uid为0，会少收到或收不到消息
改为1或其他uid就可以完整收到消息

**Comment by FishZe** [comment]
感谢提醒，是我本地修改忘记commit了:sob:

**Comment by niaiai** [comment]
现在b站的uid是int64类型

**Comment by FishZe** [comment]
> 现在b站的uid是int64类型

感谢提醒，已修复 776fee9e5b36721273f7b70c1b91571bb6183970
