### ISSUE TITLE
websocket连接错误

### ISSUE THREAD

**Issue by bighuangbee** [FishZe/go-bili-chat#40]
[bili-live][05-10 17:32:01][DEBUG]: connect to blive websocket success 
[bili-live][05-10 17:32:01][DEBUG]: send auth msg to blive success 
[bili-live][05-10 17:32:01][INFO]: connected to blive success: 32245521 
[bili-live][05-10 17:32:01][WARNING]: recv error msg:  
[bili-live][05-10 17:32:01][WARNING]: read blive websocket msg error: websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by FishZe** [comment]
请设置`cookies`和`buvid`，参考 https://github.com/FishZe/go-bili-chat/blob/3fb288675f144c37654f535a8c7633c8427a6636/example/main.go#L56 和 https://github.com/FishZe/go-bili-chat/blob/3fb288675f144c37654f535a8c7633c8427a6636/main.go#L60

**Comment by bighuangbee** [comment]
现在没有了SetHeaderCookie函数，试了下还是不行
bili.SetUID(443345583)
	//bili.SetHeader(map[string][]string{
	//	"DedeUserID__ckMd5": []string{"a08xxx"},
	//	"SESSDATA":          []string{"6f867xxx"},
	//	"bili_jct":          []string{"ab4af4xxx"},
	//	"DedeUserID":        []string{"34xxxx"},
	//})
	bili.SetHeader(map[string][]string{
		"cookie": []string{"DedeUserID__ckMd5=a08xxx; SESSDATA=6f867xxx; bili_jct=ab4af4xxx; DedeUserID=34xxxx"},
	})

**Comment by FishZe** [comment]
尝试拉取最新提交
```
go get github.com/FishZe/go-bili-chat@3fb2886
```

**Comment by bighuangbee** [comment]
请问这些值是从哪里获取的

**Comment by FishZe** [comment]
可以通过抓包软件在主站的`http`请求中获取，也可以在浏览器控制台中的`network`中查看请求，选择对应请求查看请求头获得，也可以在`Application`中查找到对应内容，`buvid`为`buvid3`，`HeaderCookie`中必须包含`SESSDATE`

**Comment by bighuangbee** [comment]
非常感谢
