### ISSUE TITLE
[Feature] 希望可以自定义 json 序列化库

### ISSUE THREAD

**Issue by XiaoMiku01** [FishZe/go-bili-chat#9]
在高并发下(例如: 同时连接 2000+ 房间时) , 官方的 `encoding/json` 性能可能跟不上，可以使用基于 `JIT` 和 `SIMD ` 的更高性能 json 序列化和反序列化库 [bytedance/sonic](https://github.com/bytedance/sonic)

**Comment by FishZe** [comment]
好的，感谢建议和提醒，马上跟进

**Comment by FishZe** [comment]
已更新 & 发布, 再次感谢您的建议

**Comment by XiaoMiku01** [comment]
emmm，如果能自定义就好了，因为。sonic 目前还不能在arm架构的机器上运行，可以实现一个接口，初始化时候传递实现该接口的 stuct

**Comment by FishZe** [comment]
哦这个意思啊...
那我再改下

**Comment by FishZe** [comment]
已更新
已在arm的路由器上测试过
